In [1]:
import numpy as np

In [6]:
#quiz1
ans=np.arange(2,11).reshape(3,3)
print(ans)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
#quiz2
ans=np.zeros(10)
ans[6]=11
print(ans)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [14]:
#quiz3
ans=np.array([1,2,0,0,4,0])
tmp=[]
for data in ans:
    if data!=0:
        tmp.append(data)
print(tmp)

[1, 2, 4]


In [15]:
import pandas as pd


In [18]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data,train_label)
pred=dt_clf.predict(train_data)

print('prediction accuracy:',accuracy_score(train_label,pred))

prediction accuracy: 1.0


In [23]:
#K Fold Cross Validation 1
from sklearn.model_selection import KFold
iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=142)

k_fold=KFold(n_splits=5)
cv_accuracy=[]
print('Iris Data Set Size:',features.shape[0])

Iris Data Set Size: 150


In [27]:
#K Fold Cross Validation 2
fold_index=0
for train_index,test_index in k_fold.split(features):
    x_train,x_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    print(train_index)
    print(test_index)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [29]:
#K Fold Cross Validation 3
fold_index=0
for train_index,test_index in k_fold.split(features):
    x_train,x_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    
    dt_clf.fit(x_train,y_train)
    pred=dt_clf.predict(x_test)
    fold_index+=1
    
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=x_train.shape[0]
    test_size=x_test.shape[0]
    
    print('\n{0} fold accuracy:{1}, train size:{2}, test size: {3}'.format(fold_index,accuracy,train_size,test_size))
    print('#{0} test index:{1}'.format(fold_index,test_index))
    
    cv_accuracy.append(accuracy)
print('\n##avg val accuracy:',np.mean(cv_accuracy))


1 fold accuracy:1.0, train size:120, test size: 30
#1 test index:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

2 fold accuracy:0.9667, train size:120, test size: 30
#2 test index:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

3 fold accuracy:0.9, train size:120, test size: 30
#3 test index:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

4 fold accuracy:0.9333, train size:120, test size: 30
#4 test index:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

5 fold accuracy:0.7667, train size:120, test size: 30
#5 test index:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

##avg val accuracy: 0.91334


In [32]:
#K Fold Cross Validation 의 한계1
import pandas as pd
iris=load_iris()
df_iris=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df_iris['label']=iris.target
df_iris['label'].value_counts()

kfold=KFold(n_splits=3)
fold_index=0
for train_index,test_index in kfold.split(df_iris):
    fold_index+=1
    label_train=df_iris['label'].iloc[train_index]
    label_test=df_iris['label'].iloc[test_index]
    print('##Cross Validation:{0}'.format(fold_index))
    print('Train label distribution:\n',label_train.value_counts())
    print('Val label distribution:\n',label_test.value_counts())
#train set과 validation set의 label 분포가 완전히 다름

##Cross Validation:1
Train label distribution:
 2    50
1    50
Name: label, dtype: int64
Val label distribution:
 0    50
Name: label, dtype: int64
##Cross Validation:2
Train label distribution:
 2    50
0    50
Name: label, dtype: int64
Val label distribution:
 1    50
Name: label, dtype: int64
##Cross Validation:3
Train label distribution:
 1    50
0    50
Name: label, dtype: int64
Val label distribution:
 2    50
Name: label, dtype: int64


In [35]:
##K Fold Cross Validation 의 한계2
from sklearn.model_selection import KFold
iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=142)

k_fold=KFold(n_splits=3,shuffle=True)
cv_accuracy=[]
print('Iris Data Set Size:',features.shape[0])
fold_index=0
for train_index,test_index in k_fold.split(features):
    x_train,x_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    
    dt_clf.fit(x_train,y_train)
    pred=dt_clf.predict(x_test)
    fold_index+=1
    
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=x_train.shape[0]
    test_size=x_test.shape[0]
    
    print('\n{0} fold accuracy:{1}, train size:{2}, test size: {3}'.format(fold_index,accuracy,train_size,test_size))
    print('#{0} test index:{1}'.format(fold_index,test_index))
    
    cv_accuracy.append(accuracy)
print('\n##avg val accuracy:',np.mean(cv_accuracy))

Iris Data Set Size: 150

1 fold accuracy:0.84, train size:100, test size: 50
#1 test index:[  6   7   8   9  22  24  25  27  29  30  37  40  41  49  50  52  53  55
  60  61  62  65  76  77  79  82  84  86  87  89  93  97  98  99 102 107
 110 113 118 120 125 129 130 133 134 136 137 139 141 149]

2 fold accuracy:0.92, train size:100, test size: 50
#2 test index:[  3   4   5  10  11  15  17  18  19  20  23  32  35  38  42  45  46  47
  48  57  58  63  64  67  68  70  71  72  75  81  83  85  94  96 100 104
 106 108 109 114 116 117 119 121 123 132 135 142 143 146]

3 fold accuracy:0.96, train size:100, test size: 50
#3 test index:[  0   1   2  12  13  14  16  21  26  28  31  33  34  36  39  43  44  51
  54  56  59  66  69  73  74  78  80  88  90  91  92  95 101 103 105 111
 112 115 122 124 126 127 128 131 138 140 144 145 147 148]

##avg val accuracy: 0.9066666666666666


In [38]:
#Stratified K Fold Cross Validation2
from sklearn.model_selection import StratifiedKFold
iris=load_iris()
features=iris.data
label=iris.target
df_clf=DecisionTreeClassifier(random_state=120)

skfold=StratifiedKFold(n_splits=3)
fold_index=0
lst_accuracy=[]

for train_index,test_index in skfold.split(features,label):
    x_train,x_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    dt_clf.fit(x_train,y_train)
    pred=dt_clf.predict(x_test)
    fold_index+=1
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=x_train.shape[0]
    test_size=y_train.shape[0]
    print('\n#{0}Cross val accuacy:{1}, train size:{2}, test size:{3}'.format(fold_index,accuracy,train_size,test_size))
    print('#{0}Val index:{1}'.format(fold_index,test_index))
    lst_accuracy.append(accuracy)
    
print('\n##fold val accuracy:',np.round(lst_accuracy,4))
print('##avg val accuracy:',np.mean(lst_accuracy))


#1Cross val accuacy:0.9804, train size:99, test size:99
#1Val index:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116]

#2Cross val accuacy:0.9216, train size:99, test size:99
#2Val index:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133]

#3Cross val accuacy:0.9792, train size:102, test size:102
#3Val index:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

##fold val accuracy: [0.9804 0.9216 0.9792]
##avg val accuracy: 0.9604


In [43]:
#cross_val_score API
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

iris=load_iris()
dt_clf=DecisionTreeClassifier(random_state=1923)
data=iris.data
label=iris.target
scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('Fold val accuracy:',np.round(scores,4))
print('Avg val accuracy:',np.round(np.mean(scores),4))

Fold val accuracy: [0.9804 0.9216 1.    ]
Avg val accuracy: 0.9673


In [49]:
#GridSearchCV() API1
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=121)
dtree=DecisionTreeClassifier()
parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

import pandas as pd
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)
grid_dtree.fit(x_train,y_train)
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]


{'mean_fit_time': array([0.00066463, 0.00032234, 0.00033132, 0.        , 0.00033236,
       0.00066392]), 'std_fit_time': array([0.00046997, 0.00045586, 0.00046856, 0.        , 0.00047002,
       0.00046946]), 'mean_score_time': array([0.        , 0.00067568, 0.000676  , 0.        , 0.        ,
       0.00033315]), 'std_score_time': array([0.        , 0.00047797, 0.00047829, 0.        , 0.        ,
       0.00047115]), 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'max_depth': 1, 'min_samples_split': 2}, {'max_depth': 1, 'min_samples_split': 3}, {'max_depth': 2, 'min_samples_split': 2}, {'max_depth': 2, 'min_samples_split': 3}, {'max_depth': 3, 'min_samples_split': 2}, {'max_dept

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [46]:
##GridSearchCV() API2: 최적의 파라미터 정보확인
print('Optimal parameter:',grid_dtree.best_params_)
print('Max accuracy:{0:.4f}'.format(grid_dtree.best_score_))

Optimal parameter: {'max_depth': 3, 'min_samples_split': 2}
Max accuracy:0.9750


In [47]:
##GridSearch() API3 : 최적의 파라미터로 학습된 모델의 성능검증
estimator=grid_dtree.best_estimator_
pred=estimator.predict(x_test)
print('Test datast accuracy:{0:.4f}'.format(accuracy_score(y_test,pred)))

Test datast accuracy:0.9667


In [50]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('Label encoding result:',labels)
print('Encoding classes:',encoder.classes_)
print('Decoding values:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

Label encoding result: [0 1 4 5 3 3 2 2]
Encoding classes: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
Decoding values: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [56]:
#One-hot encoding
from sklearn.preprocessing import OneHotEncoder
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
labels=labels.reshape(-1,1) # -1은 어느 인덱스도 될수있다는 의미

one_hot_encoder=OneHotEncoder()
one_hot_encoder.fit(labels)
one_hot_labels=one_hot_encoder.transform(labels)
print('OneHot Encoder Data')
print(one_hot_labels.toarray())
print('Dimension of Encoding Data')
print(one_hot_labels.shape)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
OneHot Encoder Data
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
Dimension of Encoding Data
(8, 6)


c:\users\sun\venv\ml\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [57]:
#pandas를 이용한 one-hot-encoding
import pandas as pd
df=pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

In [59]:
#Scaling : 특이값 처리를 위해 데이터 값의 범위를 일정한 수준으로 변환
#1.StandardScaler() api 1
#데이터 값 확인
from sklearn.datasets import load_iris
import pandas as pd
iris=load_iris()
iris_data=iris.data
df_iris=pd.DataFrame(data=iris_data,columns=iris.feature_names)

print('Average',df_iris.mean())
print('\nVariance',df_iris.var())

Average sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Variance sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [60]:
#1.StandardScaler() api2
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(df_iris)
scaled_iris=scaler.transform(df_iris)
df_scaled_iris=pd.DataFrame(data=scaled_iris,columns=iris.feature_names)
print('Average',df_scaled_iris.mean())
print('\nVariance',df_scaled_iris.var())

Average sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

Variance sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [63]:
#2. MInMaxScaler() api
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(df_iris)
scaled_iris=scaler.transform(df_iris)
df_scaled_iris=pd.DataFrame(data=scaled_iris,columns=iris.feature_names)
print('Min value',df_scaled_iris.min())
print('\nMax value',df_scaled_iris.max())
print('\nAverage value',df_scaled_iris.mean())
print('\nVariance value',df_scaled_iris.var())

Min value sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

Max value sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

Average value sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64

Variance value sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


In [64]:
import pandas as pd
tit=load("train.csv")


NameError: name 'load' is not defined